# Generated by Django 5.0.1 on 2024-01-17 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtools', '0001_initial'),
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='devtool',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='devtools.devtool', verbose_name='개발툴'),
            preserve_default=False,
        ),
    ]
