# Generated by Django 5.0.1 on 2024-01-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_idea_devtool'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='mark',
            field=models.BooleanField(default=False),
        ),
    ]
