# Generated by Django 5.0.1 on 2024-01-12 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2024), django.core.validators.MinValueValidator(1950)])),
                ('genre', models.CharField(max_length=32)),
                ('star_rating', models.FloatField()),
                ('running_time', models.IntegerField()),
                ('comment', models.TextField()),
                ('director', models.CharField(max_length=32)),
                ('actor', models.CharField(max_length=32)),
            ],
        ),
    ]
