# Generated by Django 5.0.1 on 2024-01-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devtool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='이름')),
                ('kind', models.CharField(max_length=24, verbose_name='종류')),
                ('content', models.CharField(max_length=200, verbose_name='내용')),
            ],
        ),
    ]
